/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:169a56aa-d216-4e5c-a09e-712c130e77da",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_iPDaEMnXH",
    "aws_user_pools_web_client_id": "7blenf56a82j4rtvtc96o3l4m4",
    "oauth": {}
};


export default awsmobile;
